# Generated by Django 5.1.6 on 2025-02-24 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('DSG_CODE', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('DSG_NAME', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalaryScale',
            fields=[
                ('SAL_GRADE_CODE', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('SAL_GRADE_NAME', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EMP_NUMBER', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('EMP_FIRSTNAME', models.TextField()),
                ('EMP_LASTNAME', models.TextField()),
                ('EMP_BIRTHDAY', models.DateField()),
                ('EMP_DATE_JOINED', models.DateField()),
                ('DSG_CODE', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.designation')),
            ],
        ),
        migrations.AddField(
            model_name='designation',
            name='SAL_GRADE_CODE',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.salaryscale'),
        ),
    ]
